plugin:
    name: "josephcrowell.ocrestapi::lang.plugin.name"
    description: "josephcrowell.ocrestapi::lang.plugin.description"
    author: "Joseph Crowell"
    icon: icon-cloud
    homepage: "https://computerlink.com.au"
navigation:
    ocrest-api-main:
        label: "October CMS Rest API"
        url: /josephcrowell/ocrestapi/resources
        icon: icon-cloud
        iconSvg: plugins/josephcrowell/ocrestapi/icon.svg
        permissions:
            - manage_apis
permissions:
    manage_apis:
        tab: "APIs"
        label: "Manage the API endpoints"
