list: $/josephcrowell/restapi/models/resource/columns.yaml
modelClass: JosephCrowell\RestApi\Models\Resource
title: Resources
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'josephcrowell/restapi/resources/update/:id'
