name: Resources
form: $/josephcrowell/ocrestapi/models/resource/fields.yaml
modelClass: JosephCrowell\OcRestApi\Models\Resource
defaultRedirect: josephcrowell/ocrestapi/resources
create:
    redirect: 'josephcrowell/ocrestapi/resources/update/:id'
    redirectClose: josephcrowell/ocrestapi/resources
update:
    redirect: josephcrowell/ocrestapi/resources
    redirectClose: josephcrowell/ocrestapi/resources
