name: Resources
form: $/josephcrowell/restapi/models/resource/fields.yaml
modelClass: JosephCrowell\RestApi\Models\Resource
defaultRedirect: josephcrowell/restapi/resources
create:
    redirect: 'josephcrowell/restapi/resources/update/:id'
    redirectClose: josephcrowell/restapi/resources
update:
    redirect: josephcrowell/restapi/resources
    redirectClose: josephcrowell/restapi/resources
